#!/usr/bin/env python3
"""Script to populate FC Barcelona first-team & La Masia players in Firestore."""

from google.cloud import firestore

# HARDCODED project ID string as required for Agent Platform deployment safety
PROJECT_ID = "qwiklabs-gcp-04-0fa1cb8107fc"
COLLECTION_NAME = "players"

FCB_PLAYERS = [
    # First-Team Stars & La Masia Graduates
    {
        "player_id": "lamine-yamal",
        "name": "Lamine Yamal",
        "team": "FC Barcelona",
        "position": "RW",
        "rating": 88,
        "preferred_foot": "Left",
        "pace": 92,
        "shooting": 82,
        "passing": 85,
        "dribbling": 91,
        "defending": 45,
        "physical": 70,
    },
    {
        "player_id": "gavi",
        "name": "Gavi",
        "team": "FC Barcelona",
        "position": "CM",
        "rating": 85,
        "preferred_foot": "Right",
        "pace": 78,
        "shooting": 72,
        "passing": 81,
        "dribbling": 85,
        "defending": 77,
        "physical": 82,
    },
    {
        "player_id": "pedri",
        "name": "Pedri",
        "team": "FC Barcelona",
        "position": "CM",
        "rating": 88,
        "preferred_foot": "Right",
        "pace": 79,
        "shooting": 75,
        "passing": 89,
        "dribbling": 90,
        "defending": 68,
        "physical": 71,
    },
    {
        "player_id": "pau-cubarsi",
        "name": "Pau Cubarsí",
        "team": "FC Barcelona",
        "position": "CB",
        "rating": 82,
        "preferred_foot": "Right",
        "pace": 74,
        "shooting": 42,
        "passing": 82,
        "dribbling": 76,
        "defending": 83,
        "physical": 78,
    },
    {
        "player_id": "alejandro-balde",
        "name": "Alejandro Balde",
        "team": "FC Barcelona",
        "position": "LB",
        "rating": 83,
        "preferred_foot": "Left",
        "pace": 91,
        "shooting": 58,
        "passing": 75,
        "dribbling": 82,
        "defending": 77,
        "physical": 74,
    },
    {
        "player_id": "fermin-lopez",
        "name": "Fermín López",
        "team": "FC Barcelona",
        "position": "CAM",
        "rating": 81,
        "preferred_foot": "Right",
        "pace": 81,
        "shooting": 80,
        "passing": 78,
        "dribbling": 81,
        "defending": 62,
        "physical": 73,
    },
    {
        "player_id": "marc-casado",
        "name": "Marc Casadó",
        "team": "FC Barcelona",
        "position": "CDM",
        "rating": 79,
        "preferred_foot": "Right",
        "pace": 75,
        "shooting": 65,
        "passing": 80,
        "dribbling": 78,
        "defending": 78,
        "physical": 76,
    },
    {
        "player_id": "marc-bernal",
        "name": "Marc Bernal",
        "team": "FC Barcelona",
        "position": "CDM",
        "rating": 77,
        "preferred_foot": "Left",
        "pace": 72,
        "shooting": 66,
        "passing": 79,
        "dribbling": 76,
        "defending": 77,
        "physical": 78,
    },
    {
        "player_id": "robert-lewandowski",
        "name": "Robert Lewandowski",
        "team": "FC Barcelona",
        "position": "ST",
        "rating": 88,
        "preferred_foot": "Right",
        "pace": 73,
        "shooting": 89,
        "passing": 79,
        "dribbling": 84,
        "defending": 42,
        "physical": 81,
    },
    {
        "player_id": "raphinha",
        "name": "Raphinha",
        "team": "FC Barcelona",
        "position": "LW",
        "rating": 86,
        "preferred_foot": "Left",
        "pace": 89,
        "shooting": 84,
        "passing": 83,
        "dribbling": 86,
        "defending": 52,
        "physical": 75,
    },
    {
        "player_id": "dani-olmo",
        "name": "Dani Olmo",
        "team": "FC Barcelona",
        "position": "CAM",
        "rating": 86,
        "preferred_foot": "Right",
        "pace": 78,
        "shooting": 83,
        "passing": 86,
        "dribbling": 87,
        "defending": 50,
        "physical": 68,
    },
    {
        "player_id": "frenkie-de-jong",
        "name": "Frenkie de Jong",
        "team": "FC Barcelona",
        "position": "CM",
        "rating": 87,
        "preferred_foot": "Right",
        "pace": 80,
        "shooting": 71,
        "passing": 87,
        "dribbling": 89,
        "defending": 78,
        "physical": 78,
    },
    {
        "player_id": "jules-kounde",
        "name": "Jules Koundé",
        "team": "FC Barcelona",
        "position": "RB",
        "rating": 86,
        "preferred_foot": "Right",
        "pace": 83,
        "shooting": 50,
        "passing": 76,
        "dribbling": 77,
        "defending": 86,
        "physical": 82,
    },
    {
        "player_id": "ronald-araujo",
        "name": "Ronald Araujo",
        "team": "FC Barcelona",
        "position": "CB",
        "rating": 86,
        "preferred_foot": "Right",
        "pace": 85,
        "shooting": 51,
        "passing": 65,
        "dribbling": 66,
        "defending": 87,
        "physical": 86,
    },
    {
        "player_id": "ter-stegen",
        "name": "Marc-André ter Stegen",
        "team": "FC Barcelona",
        "position": "GK",
        "rating": 89,
        "preferred_foot": "Right",
        "pace": 85,
        "shooting": 88,
        "passing": 89,
        "dribbling": 90,
        "defending": 48,
        "physical": 87,
    },
    # La Masia Rising Prospects
    {
        "player_id": "guille-fernandez",
        "name": "Guille Fernández",
        "team": "FC Barcelona (La Masia)",
        "position": "CM",
        "rating": 74,
        "preferred_foot": "Right",
        "pace": 76,
        "shooting": 71,
        "passing": 78,
        "dribbling": 78,
        "defending": 62,
        "physical": 68,
    },
    {
        "player_id": "toni-fernandez",
        "name": "Toni Fernández",
        "team": "FC Barcelona (La Masia)",
        "position": "ST",
        "rating": 73,
        "preferred_foot": "Left",
        "pace": 79,
        "shooting": 76,
        "passing": 72,
        "dribbling": 77,
        "defending": 40,
        "physical": 66,
    },
    {
        "player_id": "quim-junyent",
        "name": "Quim Junyent",
        "team": "FC Barcelona (La Masia)",
        "position": "CM",
        "rating": 72,
        "preferred_foot": "Right",
        "pace": 72,
        "shooting": 66,
        "passing": 78,
        "dribbling": 76,
        "defending": 60,
        "physical": 64,
    },
    {
        "player_id": "alexis-olmedo",
        "name": "Alexis Olmedo",
        "team": "FC Barcelona (La Masia)",
        "position": "CB",
        "rating": 72,
        "preferred_foot": "Right",
        "pace": 73,
        "shooting": 38,
        "passing": 68,
        "dribbling": 66,
        "defending": 75,
        "physical": 74,
    },
    {
        "player_id": "diego-kochen",
        "name": "Diego Kochen",
        "team": "FC Barcelona (La Masia)",
        "position": "GK",
        "rating": 71,
        "preferred_foot": "Right",
        "pace": 74,
        "shooting": 72,
        "passing": 75,
        "dribbling": 73,
        "defending": 40,
        "physical": 72,
    },
]


def add_fcb_players():
    print(f"Connecting to Firestore for project: {PROJECT_ID}...")
    db = firestore.Client(project=PROJECT_ID)
    collection_ref = db.collection(COLLECTION_NAME)

    for player in FCB_PLAYERS:
        doc_ref = collection_ref.document(player["player_id"])
        doc_ref.set(player, merge=True)
        print(f"Added player: {player['name']} ({player['team']} | {player['position']}) -> {doc_ref.path}")

    print("\nFC Barcelona & La Masia players successfully added to Firestore!")


if __name__ == "__main__":
    add_fcb_players()
